createCookie("productos",'[{"id":"1","nombre":"Video1",'+
'"tipo":"Video","transaccionalidad":"Venta","disponible":"2"},'+
'{"id":"2","nombre":"Video2",'+
'"tipo":"Video","transaccionalidad":"Prestamo","disponible":"1"},'+
'{"id":"3","nombre":"Libro1",'+
'"tipo":"Libro","transaccionalidad":"Venta","disponible":"3"},'+
'{"id":"4","nombre":"Video3",'+
'"tipo":"Video","transaccionalidad":"Prestamo","disponible":"2"},'+
'{"id":"5","nombre":"Libro2",'+
'"tipo":"Libro","transaccionalidad":"Venta","disponible":"10"}]',1);
createCookie("cantidad","[2,1,2,1,5]",1);
createCookie("precioTotal","[10.20,5.43,2.0,1,40.8]",1);
createCookie("cliente",'{"nombre":"Nicolas","identificacion":"1018453546",'+
'"correoElectronico":"nicolas.2324@gmail.com","direccion":"NN",'+
'"telefono":"6050706","tipoAfiliacion":"NN"}',1);
createCookie("elementoPago","credito",1);